# Generated by Django 3.0.3 on 2020-03-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200318_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', help_text='Ex: 123 Broad St, Newark, NJ, 07102', max_length=3000, verbose_name='Address'),
        ),
    ]
