# Generated by Django 3.0.7 on 2020-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200614_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(),
        ),
    ]
