# Generated by Django 3.0.7 on 2020-06-14 15:34

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200614_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Name of Business')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Legal Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('business_type', models.CharField(max_length=100, verbose_name='Type of Business')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('phone_number', models.CharField(help_text='Ex: 800-786-8765', max_length=10, verbose_name='Contact Phone Number')),
                ('website', models.CharField(help_text='Ex: www.example.com', max_length=30, verbose_name='Website')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name')),
                ('branch_location', models.CharField(blank=True, default='', max_length=100, verbose_name='Branch Location')),
                ('aba_number', models.CharField(blank=True, default='', max_length=100, verbose_name='ABA Number')),
                ('account_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number')),
                ('banner', models.CharField(choices=[(1, 'Please create my banners. I understand there is a cost of $25'), (2, 'No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.')], max_length=1000, verbose_name='Options')),
                ('business_structure', models.CharField(choices=[(1, 'Sole Proprietorship'), (2, 'Limited Liability Corporation'), (3, 'S Corp'), (4, 'Other')], max_length=1000, verbose_name='Business Structure')),
                ('length_of_operation', models.CharField(help_text='Ex: 10 months', max_length=100, verbose_name='Length of Operation')),
                ('number_of_employees', models.CharField(help_text='Ex: 12 employees', max_length=100, verbose_name='Number of Employees')),
                ('location_type', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Physical Location'), (2, 'Home-based'), (3, 'Online')], max_length=5, verbose_name='Does your business have a physical location? (Check all that apply)')),
                ('speical_business', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Minority Owned'), (2, 'Woman Owned'), (3, 'MWBE Certified'), (4, 'DBE Certified'), (5, 'VOSBE Certified')], max_length=9, verbose_name='Is your business: (Check all that apply)')),
                ('tax_credits', models.CharField(choices=[(1, 'On line, manually (Free)'), (2, 'Downloading the application onto my own Android (Free)'), (3, 'Fincredit’s Dedicated Device and Stand ($90)')], max_length=1000, verbose_name='Tax Credits')),
                ('rate', models.CharField(choices=[(1, 'Cost to me: 10%, Net Reward to Customer: 7.0%'), (2, 'Cost to me: 14.3%, Net Reward to Customer: 10%'), (3, 'Cost to me: 17.1%, Net Reward to Customer: 12%'), (4, 'Other')], default='', max_length=50, verbose_name='Percentage')),
                ('terms_conditions', models.CharField(choices=[(1, 'Agree'), (2, 'Disagree')], default=1, max_length=8, verbose_name='Terms & Coniditons')),
                ('approved', models.CharField(choices=[(1, 'Yes'), (2, 'No')], default=2, max_length=3, verbose_name='Application Approved')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Vendor'),
        ),
    ]
