# Generated by Django 3.0.7 on 2020-06-14 16:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_vendor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='approved',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=2, max_length=3, verbose_name='Application Approved'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.CharField(choices=[('1', 'Please create my banners. I understand there is a cost of $25'), ('2', 'No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.')], max_length=1000, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_structure',
            field=models.CharField(choices=[('1', 'Sole Proprietorship'), ('2', 'Limited Liability Corporation'), ('3', 'S Corp'), ('4', 'Other')], max_length=1000, verbose_name='Business Structure'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Physical Location'), ('2', 'Home-based'), ('3', 'Online')], max_length=5, verbose_name='Does your business have a physical location? (Check all that apply)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rate',
            field=models.CharField(choices=[('1', 'Cost to me: 10%, Net Reward to Customer: 7.0%'), ('2', 'Cost to me: 14.3%, Net Reward to Customer: 10%'), ('3', 'Cost to me: 17.1%, Net Reward to Customer: 12%'), ('4', 'Other')], default='', max_length=50, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='speical_business',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Minority Owned'), ('2', 'Woman Owned'), ('3', 'MWBE Certified'), ('4', 'DBE Certified'), ('5', 'VOSBE Certified')], max_length=9, verbose_name='Is your business: (Check all that apply)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_credits',
            field=models.CharField(choices=[('1', 'On line, manually (Free)'), ('2', 'Downloading the application onto my own Android (Free)'), ('3', 'Fincredit’s Dedicated Device and Stand ($90)')], max_length=1000, verbose_name='Tax Credits'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='terms_conditions',
            field=models.CharField(choices=[('1', 'Agree'), ('2', 'Disagree')], default=1, max_length=8, verbose_name='Terms & Coniditons'),
        ),
    ]
