# Generated by Django 3.0.7 on 2020-06-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200614_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vendor',
        ),
    ]
