# Generated by Django 3.0.7 on 2020-06-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200614_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='speical_business',
            new_name='special_business',
        ),
    ]
