# Generated by Django 3.0.7 on 2020-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200615_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(help_text='Ex: 800-786-8765', max_length=12, verbose_name='Contact Phone Number'),
        ),
    ]
