# Generated by Django 3.0.7 on 2020-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200619_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='rate',
            field=models.CharField(choices=[('Cost to me: 10%, Net Discount to Customer: 7.0%', 'Cost to me: 10%, Net Discount to Customer: 7.0%'), ('Cost to me: 14.3%, Net Discount to Customer: 10%', 'Cost to me: 14.3%, Net Discount to Customer: 10%'), ('Cost to me: 17.1%, Net Discount to Customer: 12%', 'Cost to me: 17.1%, Net Discount to Customer: 12%'), ('Other', 'Other')], default='', max_length=50, verbose_name='Percentage of Discount'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_credits',
            field=models.CharField(choices=[('On line, manually (Free)', 'On line, manually (Free)'), ('Downloading the application onto my own Android (Free)', 'Downloading the application onto my own Android (Free)'), ('Fincredit’s Dedicated Device and Stand ($90)', 'Fincredit’s Dedicated Device and Stand ($90)')], default='On line, manually (Free)', max_length=1000, verbose_name='Tax Credits'),
        ),
    ]
