# Generated by Django 3.0.7 on 2020-07-01 19:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200619_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='terms_conditions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Agree', 'Agree')], max_length=5, verbose_name='Terms & Coniditons'),
        ),
    ]
