# Generated by Django 3.0.7 on 2020-07-01 21:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200701_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.CharField(blank=True, choices=[('Please create my banners. I understand there is a cost of $25', 'Please create my banners. I understand there is a cost of $25'), ('No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.', 'No, thank you. I will email you my banners (No Cost). If I do not email you my banners within 5 business days, I authorize you to create the banners for us at the above cost of $25 for both banners.')], max_length=1000, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='terms_conditions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Agree', 'Agree')], max_length=5, verbose_name='I will honor the Shop Newark Buy Local Rebate Program by processing Shop Newark rebates in the web portal on a weekly basis. By checking below you confirm and agree to all terms and conditions.'),
        ),
    ]
