# Generated by Django 3.0.7 on 2020-06-15 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0021_auto_20200614_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=30, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('sale_type', models.CharField(choices=[('1', 'Sale'), ('2', 'Return'), ('3', 'Other')], default='1', max_length=7)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
        ),
    ]
