# Generated by Django 3.0.7 on 2020-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='sale_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Return', 'Return'), ('Other', 'Other')], default='1', max_length=7),
        ),
    ]
